# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 08:30
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models
import django.utils.timezone
import edoprofile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0010_auto_20180501_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='E-mail')),
                ('occupation', models.CharField(blank=True, max_length=300, verbose_name='Должность')),
                ('father_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Телефон')),
                ('skype', models.CharField(blank=True, max_length=100, verbose_name='Skype')),
                ('address', models.CharField(blank=True, max_length=400, null=True, verbose_name='Адрес')),
                ('color', colorfield.fields.ColorField(default='#FF0000', max_length=18, verbose_name='Цвет')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'users',
                'verbose_name': 'user',
            },
            managers=[
                ('objects', edoprofile.models.EdoUserManager()),
            ],
        ),
    ]
