# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 09:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0010_auto_20180501_1318'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editor', '0002_doc_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='u_group',
        ),
        migrations.AddField(
            model_name='doc',
            name='u_group',
            field=models.ManyToManyField(blank=True, null=True, to='auth.Group', verbose_name='Группа'),
        ),
        migrations.RemoveField(
            model_name='doc',
            name='user',
        ),
        migrations.AddField(
            model_name='doc',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
