# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 09:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_auto_20180509_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='u_group',
            field=models.ManyToManyField(blank=True, to='auth.Group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
