# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0004_auto_20180509_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Дата добавления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doc',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления'),
        ),
    ]
