# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-12 11:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editor', '0005_auto_20180510_1230'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата добавления')),
                ('previous_version', models.TextField(verbose_name='Предыдущая версия')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.Doc', verbose_name='Документ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
